c:\Users\ok974\Anaconda3\scripts\activate&pyinstaller.exe main.py --name Encrypt_pdf.exe --icon=.\Ok_64x64.ico --exclude-module=PySide2 --add-data=.\Ok_64x64.ico;. --distpath c:\codepy\00_EXECUTABLE_FILE --noconsole --onefile
set /p DUMMY=Hit ENTER to continue...
